import test from 'node:test';
import assert from 'node:assert/strict';
import { applyGraphFilters } from '../src/lib/graphFilters.ts';
import type { GraphSnapshot } from '../src/types.ts';

const snapshot: GraphSnapshot = {
  run_id: 'run-1',
  mode: 'focus',
  view_mode: 'intervention',
  focus_kind: 'cluster',
  focus_id: 'cluster-review',
  nodes: [
    {
      id: 'source-a',
      kind: 'source',
      label: 'Alpha',
      title: 'Alpha Inc',
      status: 'matched',
      status_label: 'Matched',
      status_tone: 'positive',
      is_aggregate: false,
      phase: 'main',
      anomaly_count: 0,
      member_count: 1,
      preview_items: [],
      overflow_count: 0,
      saved_by_agent_count: 0,
      saved_by_human_count: 0,
      still_blocked_count: 0,
      rejected_count: 0,
      pending_review_count: 0,
      badges: [],
      preview_metrics: [],
      meta: {},
    },
    {
      id: 'source-b',
      kind: 'source',
      label: 'Beta',
      title: 'Beta Inc',
      status: 'needs_review',
      status_label: 'Needs review',
      status_tone: 'warning',
      is_aggregate: false,
      phase: 'main',
      anomaly_count: 1,
      member_count: 1,
      preview_items: [],
      overflow_count: 0,
      saved_by_agent_count: 0,
      saved_by_human_count: 0,
      still_blocked_count: 0,
      rejected_count: 0,
      pending_review_count: 0,
      badges: [],
      preview_metrics: [],
      meta: {},
    },
    {
      id: 'cluster-review',
      kind: 'cluster',
      label: 'Review group',
      title: 'Review group',
      status: 'needs_review',
      status_label: 'Needs review',
      status_tone: 'warning',
      is_aggregate: false,
      phase: 'main',
      anomaly_count: 1,
      member_count: 2,
      preview_items: [],
      overflow_count: 0,
      saved_by_agent_count: 1,
      saved_by_human_count: 1,
      still_blocked_count: 0,
      rejected_count: 0,
      pending_review_count: 1,
      intervention_summary_label: 'Pending 1',
      badges: [],
      preview_metrics: [],
      meta: { cluster_id: 'cluster-review' },
    },
    {
      id: 'company-1',
      kind: 'master',
      label: 'Company 1',
      title: 'Company 1',
      status: 'matched',
      status_label: 'Matched',
      status_tone: 'positive',
      is_aggregate: false,
      phase: 'main',
      anomaly_count: 0,
      member_count: 2,
      preview_items: [],
      overflow_count: 0,
      saved_by_agent_count: 1,
      saved_by_human_count: 1,
      still_blocked_count: 0,
      rejected_count: 1,
      pending_review_count: 0,
      intervention_summary_label: 'Agent saved 1',
      badges: [],
      preview_metrics: [],
      meta: { entity_id: 'company-1' },
    },
  ],
  edges: [
    {
      id: 'membership-1',
      source: 'source-b',
      target: 'cluster-review',
      kind: 'membership',
      status: 'needs_review',
      display_status: 'Joined group',
      status_tone: 'muted',
      is_aggregate: false,
      edge_count: 1,
      summary_status: 'needs_review',
      intervention_kind: 'none',
      intervention_actor: 'none',
      intervention_outcome: 'none',
      outcome_effect: 'no_change',
      audit_refs: [],
      meta: {},
    },
    {
      id: 'assignment-1',
      source: 'cluster-review',
      target: 'company-1',
      kind: 'assignment',
      status: 'matched',
      display_status: 'Matched company',
      status_tone: 'muted',
      is_aggregate: false,
      edge_count: 1,
      summary_status: 'matched',
      intervention_kind: 'none',
      intervention_actor: 'none',
      intervention_outcome: 'none',
      outcome_effect: 'no_change',
      audit_refs: [],
      meta: {},
    },
    {
      id: 'review-agent',
      source: 'source-b',
      target: 'company-1',
      kind: 'to_master',
      status: 'resolved',
      display_status: 'Resolved',
      status_tone: 'positive',
      is_aggregate: false,
      edge_count: 1,
      summary_status: 'resolved',
      intervention_kind: 'agent',
      intervention_actor: 'context_agent',
      intervention_outcome: 'saved',
      outcome_effect: 'matched_company',
      pre_review_status: 'blocked',
      post_review_status: 'resolved',
      decision_summary: 'Context agent saved this path and it helped the group match a company.',
      audit_refs: [],
      meta: {},
    },
    {
      id: 'review-human',
      source: 'source-a',
      target: 'company-1',
      kind: 'to_master',
      status: 'resolved',
      display_status: 'Resolved',
      status_tone: 'info',
      is_aggregate: false,
      edge_count: 1,
      summary_status: 'resolved',
      intervention_kind: 'human',
      intervention_actor: 'human',
      intervention_outcome: 'saved',
      outcome_effect: 'matched_company',
      pre_review_status: 'blocked',
      post_review_status: 'resolved',
      review_case_id: 'case-1',
      decision_summary: 'Human review saved this path and it helped the group match a company.',
      audit_refs: [],
      meta: {},
    },
    {
      id: 'review-rejected',
      source: 'source-b',
      target: 'source-a',
      kind: 'peer',
      status: 'rejected',
      display_status: 'Rejected',
      status_tone: 'danger',
      is_aggregate: false,
      edge_count: 1,
      summary_status: 'rejected',
      intervention_kind: 'human',
      intervention_actor: 'human',
      intervention_outcome: 'rejected',
      outcome_effect: 'prevented_bad_match',
      pre_review_status: 'blocked',
      post_review_status: 'rejected',
      review_case_id: 'case-2',
      decision_summary: 'Human review rejected this path to prevent a bad match.',
      audit_refs: [],
      meta: {},
    },
  ],
  stats: {},
};

test('intervention outcome filter keeps matching intervention edges and context nodes', () => {
  const result = applyGraphFilters(snapshot, {
    viewMode: 'intervention',
    outcomeFilter: 'saved_by_agent',
    actorFilter: 'all',
    impactFilter: 'all',
    edgeKindFilter: 'all',
    rawStatusFilter: 'all',
    phaseFilter: 'all',
  });

  assert.deepEqual(result.edges.map((edge) => edge.id).sort(), ['assignment-1', 'membership-1', 'review-agent']);
  assert.ok(result.nodes.some((node) => node.id === 'company-1'));
});

test('intervention actor filter isolates human-reviewed paths', () => {
  const result = applyGraphFilters(snapshot, {
    viewMode: 'intervention',
    outcomeFilter: 'all',
    actorFilter: 'human',
    impactFilter: 'all',
    edgeKindFilter: 'all',
    rawStatusFilter: 'all',
    phaseFilter: 'all',
  });

  assert.deepEqual(result.edges.map((edge) => edge.id).sort(), ['assignment-1', 'membership-1', 'review-human', 'review-rejected']);
});

test('structure mode uses raw status and edge kind filters', () => {
  const result = applyGraphFilters(snapshot, {
    viewMode: 'structure',
    outcomeFilter: 'all',
    actorFilter: 'all',
    impactFilter: 'all',
    edgeKindFilter: 'peer',
    rawStatusFilter: 'rejected',
    phaseFilter: 'all',
  });

  assert.deepEqual(result.edges.map((edge) => edge.id), ['review-rejected']);
});
